### PR TITLE
Fix licensing and make pure Py3 wheel

### PR DESCRIPTION
**Pull request by Zeitsperre**

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@davidcaron If you have a PyPI username, send that to me so you can at least have push rights on the package there.

**Comment by davidcaron** [comment]
it's davidcaron, same as on github

**Comment by Zeitsperre** [comment]
Done. https://pypi.org/project/requests-mapgie/

**Comment by tlvu** [comment]
Awsome !  I suppose the `0.1.0.dev0` version is temporary and eventually we will push another nicer looking version with proper tagging?

Thanks to both of you.

**Comment by davidcaron** [comment]
Thanks! @tlvu you can change your requirements files to use `requests-magpie`

**Comment by davidcaron** [comment]
> Awsome ! I suppose the `0.1.0.dev0` version is temporary and eventually we will push another nicer looking version with proper tagging?

I'll push a 0.1.0 tomorrow, no problem.

**Pull request merged**
